# Netlify Configuration File
[build]
  # Build command (leave empty for static sites)
  command = ""
  
  # Directory to publish (root directory for static HTML sites)
  publish = "."
  
  # Functions directory (not needed for this project)
  functions = ""

[build.environment]
  # Environment variables (add any you need)
  NODE_VERSION = "18"

# Redirect rules
[[redirects]]
  # Redirect admin paths to admin/index.html
  from = "/admin"
  to = "/admin/index.html"
  status = 200

[[redirects]]
  # Handle SPA routing (if needed)
  from = "/*"
  to = "/index.html"
  status = 200
  conditions = {Role = ["admin"]}

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.html"
  [headers.values]
    Cache-Control = "public, max-age=3600"

# Development settings
[dev]
  command = "python3 -m http.server 8000"
  port = 8000
  publish = "."
